API_KEYS:
  # API KEYS
  # OpenAI API KEY
  openai_api_key: YOUR_API_KEY
  # Google API KEY
  google_api_key: YOUR_API_KEY
  # Claude API KEY
  claude_api_key: YOUR_API_KEY
  # Lunary API KEY 
  lunary_api_key: YOUR_API_KEY

MODEL:
  # LLM to be used 'gpt-4'
  model: gpt-4
  # Model temperature
  temp: 0.75
  # Number of attempts/samples
  K_run: 5
  # top_p (0,1) default: 1
  top_p: 1
  # Adjustable number of tokens to control response length
  max_tokens: 4000
  # Number of completions to generate
  n: 1
  # Stop completion tokens
  stop: null
  # Waiting time
  cool_down_time: 3

ENVIRONMENT:
  # Filesystems task JSON path (absolute path)
  task_path: path_to_task_json
  # Base output path (absolute path)
  base_output_path: path_to_output
  # Effectful interface API path (absolute path)
  interface_path: path_to_effectful_interface

FEWSHOT:
  # Required for dynamic Few-Shot RAG Prompting
  # Example CWEs JSON path (absolute path)
  RAG_json_path: path_to_RAG_samples_json
  # TODO: Add a RAG for fixing generated errors during compilation
  # Filesystem API reference path (absolute path)
  api_reference_path: path_to_effectful_interface_api_json
  # Number of code examples in [Chain of Thought (CoT) Prompt]
  few_shot_examples_count: 5
